# Generated by Django 5.2.6 on 2025-09-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
