# Generated by Django 5.2.6 on 2025-09-19 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpcode_users_otpco_contact_89a347_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('login_locked', 'Account Locked'), ('password_changed', 'Password Changed'), ('otp_sent', 'OTP Sent'), ('otp_failed', 'OTP Verification Failed'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('suspicious_activity', 'Suspicious Activity'), ('account_unlocked', 'Account Unlocked'), ('session_created', 'Session Created'), ('session_terminated', 'Session Terminated')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='users_secur_event_t_46a1ec_idx'), models.Index(fields=['severity'], name='users_secur_severit_a6b8d2_idx'), models.Index(fields=['ip_address'], name='users_secur_ip_addr_90c612_idx'), models.Index(fields=['created_at'], name='users_secur_created_a22133_idx'), models.Index(fields=['user', 'event_type'], name='users_secur_user_id_adaebc_idx')],
            },
        ),
    ]
