# Generated by Django 5.2.6 on 2025-09-19 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_security_log_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('login_locked', 'Account Locked'), ('password_changed', 'Password Changed'), ('otp_sent', 'OTP Sent'), ('otp_failed', 'OTP Verification Failed'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('suspicious_activity', 'Suspicious Activity'), ('account_unlocked', 'Account Unlocked'), ('session_created', 'Session Created'), ('session_terminated', 'Session Terminated'), ('email_verification_sent', 'Email Verification Sent'), ('email_verified', 'Email Verified'), ('phone_verification_sent', 'Phone Verification Sent'), ('phone_verified', 'Phone Verified')], max_length=30),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='users_email_token_c6eae7_idx'), models.Index(fields=['email'], name='users_email_email_f14d0c_idx'), models.Index(fields=['expires_at'], name='users_email_expires_7cc044_idx'), models.Index(fields=['used'], name='users_email_used_cb0641_idx')],
            },
        ),
    ]
