# Generated by Django 5.2.6 on 2025-09-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_add_email_verification_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['created_at'], name='users_otpco_created_e8289c_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['contact_info', 'purpose', 'used'], name='users_otpco_contact_967693_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['expires_at', 'used'], name='users_otpco_expires_3d0d10_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['ip_address', 'created_at'], name='users_otpco_ip_addr_cfc201_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['event_type', 'severity'], name='users_secur_event_t_53090e_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['ip_address', 'event_type'], name='users_secur_ip_addr_5d4cac_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['created_at', 'severity'], name='users_secur_created_7b9aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['user', 'created_at'], name='users_secur_user_id_ea85cd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login'], name='users_user_last_lo_5f84ec_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='users_user_date_jo_064c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='users_user_email_3f6199_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone', 'is_active'], name='users_user_phone_2b7e95_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified', 'phone_verified'], name='users_user_email_v_3af97b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['created_at'], name='users_users_created_5cc779_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='users_users_user_id_3887fe_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['ip_address', 'is_active'], name='users_users_ip_addr_d9db35_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity', 'is_active'], name='users_users_last_ac_30d852_idx'),
        ),
    ]
